// web/src/errors/register/errors.ts
import { createIrisErrorMap } from "@/errors/core";

export const REGISTER_ERRORS = createIrisErrorMap({
  REGISTER_SCHEMA_REFINEMENT_FAILURE: {
    code: "IRIS_ERR_REGISTER_001",
    scope: "register",
    severity: "error",
    userMessage: {
      ptBR: "Revise os dados obrigatórios antes de concluir o cadastro.",
      enUS: "Review the required fields before completing registration.",
    },
    technicalMessage: "Onboarding schema validation/refinement failed.",
    possibleCause: "Etapa incompleta, senha divergente, termos não aceitos ou fluxo interno/externo inconsistente.",
    recoveryHint: "Verificar onboarding.schema.ts e mensagens de Zod.",
    shouldExposeToUser: true,
  },
  REGISTER_SUPABASE_NOT_CONFIGURED: {
    code: "IRIS_ERR_REGISTER_002",
    scope: "register",
    severity: "critical",
    userMessage: {
      ptBR: "Supabase não configurado. Verifique as variáveis públicas do web.",
      enUS: "Supabase is not configured. Check the public web environment variables.",
    },
    technicalMessage: "Supabase browser client could not be created in register flow.",
    possibleCause: "NEXT_PUBLIC_SUPABASE_URL ou NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ausente/inválida.",
    recoveryHint: "Corrigir web/.env.local e reiniciar o servidor.",
    shouldExposeToUser: true,
  },
  REGISTER_SIGNUP_FAILED: {
    code: "IRIS_ERR_REGISTER_003",
    scope: "register",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível criar a conta. Verifique o e-mail ou tente novamente.",
      enUS: "Unable to create the account. Check the email or try again.",
    },
    technicalMessage: "Supabase Auth signUp failed.",
    possibleCause: "E-mail já cadastrado, senha inválida, SMTP/confirm email ou regra do Auth.",
    recoveryHint: "Checar Auth logs no Supabase e retorno de signUp.",
    shouldExposeToUser: true,
  },
  REGISTER_USERNAME_UNAVAILABLE: {
    code: "IRIS_ERR_REGISTER_004",
    scope: "register",
    severity: "warning",
    userMessage: {
      ptBR: "Escolha outro @ antes de concluir.",
      enUS: "Choose another username before completing.",
    },
    technicalMessage: "Username availability check returned unavailable.",
    possibleCause: "Já existe admin_profiles.username igual.",
    recoveryHint: "Consultar admin_profiles por username normalizado.",
    shouldExposeToUser: true,
  },
  REGISTER_SESSION_MISSING_AFTER_SIGNUP: {
    code: "IRIS_ERR_REGISTER_005",
    scope: "register",
    severity: "info",
    userMessage: {
      ptBR: "Conta criada. Confirme seu e-mail e depois faça login para concluir o onboarding.",
      enUS: "Account created. Confirm your email and then sign in to complete onboarding.",
    },
    technicalMessage: "signUp completed without active session.",
    possibleCause: "Supabase Auth está exigindo confirmação de e-mail.",
    recoveryHint: "Criar fluxo de retomada após confirmação de e-mail.",
    shouldExposeToUser: true,
  },
  REGISTER_COMPLETE_API_FAILED: {
    code: "IRIS_ERR_REGISTER_006",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível concluir o onboarding.",
      enUS: "Unable to complete onboarding.",
    },
    technicalMessage: "POST /api/onboarding/complete failed.",
    possibleCause: "Service role ausente, RLS, tabela ausente, schema SQL não aplicado ou payload inválido.",
    recoveryHint: "Verificar terminal Next, SQL Supabase e rota /api/onboarding/complete.",
    shouldExposeToUser: true,
  },
  REGISTER_USERNAME_CHECK_FAILED: {
    code: "IRIS_ERR_REGISTER_007",
    scope: "onboarding",
    severity: "warning",
    userMessage: {
      ptBR: "Não foi possível verificar o @ agora.",
      enUS: "Unable to check the username right now.",
    },
    technicalMessage: "GET /api/onboarding/username/check failed.",
    possibleCause: "Service role ausente, tabela admin_profiles não criada ou falha na API.",
    recoveryHint: "Verificar terminal Next e SQL da tabela admin_profiles.",
    shouldExposeToUser: true,
  },
  REGISTER_CEP_LOOKUP_FAILED: {
    code: "IRIS_ERR_REGISTER_008",
    scope: "register",
    severity: "info",
    userMessage: {
      ptBR: "Não foi possível buscar o CEP automaticamente. Você pode preencher o endereço manualmente.",
      enUS: "Unable to fetch CEP automatically. You can fill the address manually.",
    },
    technicalMessage: "ViaCEP lookup failed.",
    possibleCause: "CEP inválido, ViaCEP fora do ar ou falha de rede.",
    recoveryHint: "Permitir preenchimento manual sem bloquear onboarding.",
    shouldExposeToUser: false,
  },
  REGISTER_SERVER_AUTH_MISSING: {
    code: "IRIS_ERR_REGISTER_009",
    scope: "onboarding",
    severity: "warning",
    userMessage: {
      ptBR: "Sessão ausente. Faça login novamente.",
      enUS: "Missing session. Please sign in again.",
    },
    technicalMessage: "Missing Bearer token in onboarding complete route.",
    possibleCause: "Usuário sem sessão ativa ou token não enviado no fetch.",
    recoveryHint: "Checar session.access_token antes de chamar /api/onboarding/complete.",
    shouldExposeToUser: true,
  },
  REGISTER_SERVER_SUPABASE_ADMIN_MISSING: {
    code: "IRIS_ERR_REGISTER_010",
    scope: "onboarding",
    severity: "critical",
    userMessage: {
      ptBR: "Configuração server-side do Supabase ausente.",
      enUS: "Server-side Supabase configuration is missing.",
    },
    technicalMessage: "Supabase admin client could not be created.",
    possibleCause: "SUPABASE_SERVICE_ROLE_KEY ou SUPABASE_SECRET_KEY ausente.",
    recoveryHint: "Adicionar chave server-side sem NEXT_PUBLIC e reiniciar o servidor.",
    shouldExposeToUser: true,
  },
  REGISTER_PROFILE_SAVE_FAILED: {
    code: "IRIS_ERR_REGISTER_011",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível salvar o perfil administrativo.",
      enUS: "Unable to save the admin profile.",
    },
    technicalMessage: "Upsert admin_profiles failed.",
    possibleCause: "Tabela ausente, constraint violada, username duplicado ou enum incompatível.",
    recoveryHint: "Verificar SQL, constraints e payload enviado.",
    shouldExposeToUser: true,
  },
  REGISTER_PRIVATE_DETAILS_SAVE_FAILED: {
    code: "IRIS_ERR_REGISTER_012",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível salvar os dados privados.",
      enUS: "Unable to save private details.",
    },
    technicalMessage: "Upsert admin_private_personal_details failed.",
    possibleCause: "Tabela ausente, CPF hash inválido ou policy/constraint incorreta.",
    recoveryHint: "Verificar SQL e payload de dados privados.",
    shouldExposeToUser: true,
  },
  REGISTER_PREFERENCES_SAVE_FAILED: {
    code: "IRIS_ERR_REGISTER_013",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível salvar as preferências.",
      enUS: "Unable to save preferences.",
    },
    technicalMessage: "Upsert admin_notification_preferences failed.",
    possibleCause: "Tabela ausente, enum de frequência incompatível ou payload inválido.",
    recoveryHint: "Verificar SQL e notificationFrequency.",
    shouldExposeToUser: true,
  },
  REGISTER_ORGANIZATION_SAVE_FAILED: {
    code: "IRIS_ERR_REGISTER_014",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível criar a organização.",
      enUS: "Unable to create organization.",
    },
    technicalMessage: "Insert admin_organizations failed.",
    possibleCause: "Tabela ausente, CNPJ inválido, service role ausente ou constraint violada.",
    recoveryHint: "Verificar SQL, CNPJ normalizado e chave server-side.",
    shouldExposeToUser: true,
  },
  REGISTER_ORGANIZATION_MEMBER_SAVE_FAILED: {
    code: "IRIS_ERR_REGISTER_015",
    scope: "onboarding",
    severity: "error",
    userMessage: {
      ptBR: "Não foi possível vincular usuário à organização.",
      enUS: "Unable to link user to organization.",
    },
    technicalMessage: "Insert admin_organization_members failed.",
    possibleCause: "organization_id inválido, user_id inválido ou unique constraint.",
    recoveryHint: "Verificar criação da organização antes do vínculo.",
    shouldExposeToUser: true,
  },
} as const);

export type RegisterErrorKey = keyof typeof REGISTER_ERRORS;
